name: CI

on:
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: 🔨 Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Build app with Gradle
        run: ./gradlew assembleDebug --stacktrace

  unit-tests:
    name: 🧪 Run Tests
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Execute unit tests
        run: ./gradlew testDebug

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}
