name: CI

on:
  pull_request:
  merge_group:
    branches: [ master ]

jobs:

  build:
    name: 🔨 Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Access THEMOVIEDB_API_KEY
        env:
          THEMOVIEDB_API_KEY: $
        run: echo THEMOVIEDB_API_KEY=\"THEMOVIEDB_API_KEY\" > ./././secrets.properties

      - name: Build app with Gradle
        run: ./gradlew assembleDebug --stacktrace

  unit-tests:
    name: 🧪 Run Tests
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Access THEMOVIEDB_API_KEY
        env:
          THEMOVIEDB_API_KEY: $
        run: echo THEMOVIEDB_API_KEY=\"THEMOVIEDB_API_KEY\" > ./././secrets.properties

      - name: Execute unit tests
        run: ./gradlew testDebug

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}
